app = "road-to-glory-postgres"

kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = "http"
    handlers = ["http"]

[[services]]
  internal_port = 5433
  protocol = "tcp"

  [[services.ports]]
    port = "postgres"
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = 2000
    command = '''\
      bash -c '
      </dev/tcp/127.0.0.1/5433 && echo -e "HEAD / HTTP/1.1\nHost: localhost\n\n" | nc localhost 5433 > /dev/null
      '
    '''